### ISSUE TITLE
如何参与一起翻译？

### ISSUE THREAD

**Issue by qiuyuntao** [react-guide/ETC#1]
如题

**Comment by camsong** [comment]
现在有2个项目
- https://github.com/react-guide/react-router-cn
- https://github.com/camsong/redux-in-chinese

你可以找对应项目的 Issue，如果没被认领，可以回复认领，具体操作见 [加入翻译](https://github.com/react-guide/ETC#加入翻译)

现在这个 Issue 是待认领状态，欢迎参与啊 https://github.com/react-guide/react-router-cn/issues/11

**Comment by qiuyuntao** [comment]
ok @camsong
