### ISSUE TITLE
认领翻译

### ISSUE THREAD

**Issue by viddamao** [react-guide/ETC#2]
redux-tutorial-cn/11_src/src中的翻译

**Comment by camsong** [comment]
Hi @viddamao，认领翻译请到对应项目里开 issue

**Comment by viddamao** [comment]
额不好意思啊哈哈，开了太多窗口点错了

Sent from Mail Master

在2016年07月06日 10:01 ，Cam Songmailto:notifications@github.com写道：

Hi @viddamaohttps://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_viddamao&d=CwMFaQ&c=imBPVzF25OnBgGmVOlcsiEgHoG1i6YHLR0Sj_gZ4adc&r=BhL0t_roeBndPJ8043_Yuw&m=-vAbTGqqBj1zvlWSbPp4HI7KiHPCv_vug7uZdDXZcM0&s=m70QlcD2lWC2KSyrlxgsH5ugVOaMK3DQYl_5dHC-kS0&e=，认领翻译请到对应项目里开 issue
