### ISSUE TITLE
在操作系统Windows上build的时候，出现Template render error异常

### ISSUE THREAD

**Issue by creamidea** [react-guide/ETC#3]
在操作系统 Windows 上编辑文档，保存时文件一般以 `CRLF` 形式保存。而这个在 **gitbook** 生成引擎中存在一个 bug（或者说是 feature？）。详见[这里](https://github.com/GitbookIO/gitbook-markdown/issues/2)。

修复方式：
根据异常提示，找出出错的文件。更改 `CRLF` 为 `LF` 即可。

PS：
大部分编辑器，如： Sublime Text, Atom, VSCode等在底部状态栏中都有直接可以操作的按钮，点击修改保存即可。

其它编辑器请自行搜索解决 :P

**Comment by creamidea** [comment]
如果你使用的是 **Emacs** 编辑器，你可以点击[这里](https://www.emacswiki.org/emacs/EndOfLineTips)了解更多。
- `M-x set-buffer-file-coding-system utf-8-unix` (for LF)
- `M-x set-buffer-file-coding-system utf-8-mac` (for CR)
- `M-x set-buffer-file-coding-system utf-8-dos` (for CR+LF)

（这真是一个分裂的世界 :_）

**Comment by nijisakai** [comment]
awesome man
